"""Share: generate shareable HTML report from lockfile.

Creates a self-contained HTML report with environment details,
feasibility summary, and package lists. Works fully offline.
"""

import datetime
import html
import json
import os
import shutil
import zipfile

from rich.console import Console

from repro import lockfile

console = Console()


def _generate_html(data: dict) -> str:
    """Generate a self-contained HTML report from lockfile data."""
    sys_info = data.get("system", {})
    langs = data.get("languages", {})
    pm = data.get("package_managers", {})
    tools = data.get("tools", {})

    # Build package rows
    pip_rows = ""
    for name, ver in sorted(pm.get("pip", {}).items()):
        pip_rows += "<tr><td>{}</td><td>{}</td></tr>\n".format(
            html.escape(str(name)), html.escape(str(ver)))

    conda_rows = ""
    conda_pkgs = pm.get("conda", {}).get("packages", {})
    for name, ver in sorted(conda_pkgs.items()):
        conda_rows += "<tr><td>{}</td><td>{}</td></tr>\n".format(
            html.escape(str(name)), html.escape(str(ver)))

    lang_rows = ""
    for name, info in sorted(langs.items()):
        ver = info.get("version", "N/A") if isinstance(info, dict) else info
        found = info.get("found", True) if isinstance(info, dict) else True
        if found:
            lang_rows += "<tr><td>{}</td><td>{}</td></tr>\n".format(
                html.escape(str(name)), html.escape(str(ver)))

    tool_rows = ""
    for category, cat_tools in tools.items():
        if not isinstance(cat_tools, dict):
            continue
        for name, info in sorted(cat_tools.items()):
            if isinstance(info, dict) and info.get("found"):
                tool_rows += "<tr><td>{}</td><td>{}</td><td>{}</td></tr>\n".format(
                    html.escape(str(category)),
                    html.escape(str(name)),
                    html.escape(str(info.get("version", "N/A"))))

    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>repro Environment Report</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; }}
h1 {{ color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }}
h2 {{ color: #1e40af; margin-top: 30px; }}
table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f0f4ff; font-weight: 600; }}
tr:nth-child(even) {{ background: #f9fafb; }}
.meta {{ color: #6b7280; font-size: 0.9em; }}
.badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px;
          font-size: 0.85em; font-weight: 600; }}
.badge-ok {{ background: #dcfce7; color: #166534; }}
.badge-warn {{ background: #fef3c7; color: #92400e; }}
</style>
</head>
<body>
<h1>repro Environment Report</h1>
<p class="meta">Generated: {created} | Schema: {schema} | repro {version}</p>

<h2>System</h2>
<table>
<tr><th>Property</th><th>Value</th></tr>
<tr><td>OS</td><td>{os} ({os_family})</td></tr>
<tr><td>Kernel</td><td>{kernel}</td></tr>
<tr><td>Architecture</td><td>{arch}</td></tr>
<tr><td>CPUs</td><td>{cpus}</td></tr>
<tr><td>RAM</td><td>{ram}GB</td></tr>
<tr><td>Disk Free</td><td>{disk}GB</td></tr>
<tr><td>WSL</td><td>{wsl}</td></tr>
<tr><td>ARM</td><td>{arm}</td></tr>
</table>

<h2>Languages</h2>
<table>
<tr><th>Language</th><th>Version</th></tr>
{lang_rows}
</table>

<h2>Pip Packages ({pip_count})</h2>
<table>
<tr><th>Package</th><th>Version</th></tr>
{pip_rows}
</table>

<h2>Conda Packages ({conda_count})</h2>
<table>
<tr><th>Package</th><th>Version</th></tr>
{conda_rows}
</table>

<h2>Tools</h2>
<table>
<tr><th>Category</th><th>Tool</th><th>Version</th></tr>
{tool_rows}
</table>

<p class="meta">Report generated by <a href="https://github.com/usarmydoc/repro">repro</a></p>
</body>
</html>""".format(
        created=html.escape(str(data.get("created_at", "unknown"))),
        schema=html.escape(str(data.get("repro_schema_version", "?"))),
        version=html.escape(str(data.get("repro_version", "?"))),
        os=html.escape(str(sys_info.get("os", "?"))),
        os_family=html.escape(str(sys_info.get("os_family", "?"))),
        kernel=html.escape(str(sys_info.get("kernel", "?"))),
        arch=html.escape(str(sys_info.get("arch", "?"))),
        cpus=sys_info.get("cpus", "?"),
        ram=sys_info.get("ram_gb", "?"),
        disk=sys_info.get("disk_free_gb", "?"),
        wsl=sys_info.get("wsl", False),
        arm=sys_info.get("arm", False),
        lang_rows=lang_rows,
        pip_count=len(pm.get("pip", {})),
        pip_rows=pip_rows,
        conda_count=len(conda_pkgs),
        conda_rows=conda_rows,
        tool_rows=tool_rows,
    )


def run_share(lockfile_path: str, output: str = "repro_report"):
    """Generate shareable HTML report and zip archive."""
    data = lockfile.read_or_exit(lockfile_path)

    # Generate HTML
    html_content = _generate_html(data)

    # Create output directory
    os.makedirs(output, exist_ok=True)

    # Write HTML
    html_path = os.path.join(output, "report.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    # Copy lockfile
    shutil.copy2(lockfile_path, os.path.join(output, "repro.lock"))

    # Create zip
    zip_path = output + ".zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(html_path, "repro_report/report.html")
        zf.write(lockfile_path, "repro_report/repro.lock")

    zip_size = os.path.getsize(zip_path)
    console.print("[green]Report generated:[/green]")
    console.print("  HTML: {}".format(html_path))
    console.print("  ZIP:  {} ({:.1f} KB)".format(zip_path, zip_size / 1024))
